server.port=8090
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.show-details=always
logging.level.com.checkout=INFO
logging.pattern.level=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [correlation-id=%X{correlation-id}] %logger{36} - %msg%n